language: python
python:
    - 2.7
    - 3.5
    - 3.6
    - 3.7
    - 3.8
addons:
    apt:
        sources:
            - google-chrome
        packages:
            - google-chrome-stable
before_script:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb -start
    - sleep 3
before_install:
    - python --version
    - pip install -U pip
    - pip install -U pytest
    - pip install codecov
install:
    - pip install Cython
    - pip install -r requirements.txt
    - pip install ".[test]" .
script: pytest
after_success:
    - codecov