
[tool.poetry]
name = "yahooquery"
version = "2.2.14"
description = "Python interface to unofficial Yahoo Finance API endpoints"
authors = ["Doug Guthrie <douglas.p.guthrie@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.6.1,<4.0"
lxml = ">=4.6.2"
pandas = ">=1.1.5,<2"
requests-futures = ">=1.0.0,<2"
tqdm = ">=4.54.1,<5"
pytest-env = "^0.6.2"
mkdocs-material = "^6.2.8"
python-dateutil = "^2.8.1"

[tool.poetry.dev-dependencies]
pytest = "^6.2.2"
flake8 = "^3.8.4"
pre-commit = "^2.10.1"
isort = "^5.7.0"
jupyter = "^1.0.0"
pytest-cov = "^2.11.1"
pytest-env = "^0.6.2"
mypy = "^0.800"
mkdocs = "^1.1.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
